### ISSUE TITLE
License

### ISSUE THREAD

**Issue by 89z** [sunfish-shogi/bufseekio#1]
Please add license file to enable documentation:

https://pkg.go.dev/github.com/sunfish-shogi/bufseekio

**Comment by sunfish-shogi** [comment]
I added the license file.
https://github.com/sunfish-shogi/bufseekio/blob/main/LICENSE

**Comment by 89z** [comment]
Can you please add release as well:

https://github.com/sunfish-shogi/bufseekio/releases

**Comment by sunfish-shogi** [comment]
I created first release: https://github.com/sunfish-shogi/bufseekio/releases/tag/v0.1.0

**Comment by 89z** [comment]
thank you!
